### ISSUE TITLE
Error converting mp3

### ISSUE THREAD

**Issue by Danny-P** [wiro-consultants/html5mediaelements#2]
Hi! 

I'm trying to use the cron job to convert audio files to web optimated formats. 
But I'm getting the following error: 
During the conversion the following error occured:
Encoding failed and an error was returned from ffmpeg. Error code 1 was returned the message (if any) was: Error while opening encoder for output stream # 1:0 - maybe incorrect parameters such as bit_rate, rate, width or height

Which settings have I missed and where to set them? 

Thank you!

**Comment by s2b** [comment]
Did you use the default page TSconfig or did you specify your own conversion configuration? If so, could you share your audio configuration?

**Comment by Danny-P** [comment]
In my template I included the static Template html5mediaelements. 
I didn't include more TSconfig or something else. I'd like to use the default variants. As I understood the documentation, I don't have to do any more for this.

**Comment by s2b** [comment]
Did you check if your ffmpeg installation supports your input format? e. g.

`ffmpeg -i your-file.ext -acodec mp3 newfile.mp3`

**Comment by Danny-P** [comment]
Yes, I have checked it. By using your command I get the file converted correctly.

**Comment by s2b** [comment]
Could you add this snippet to your page TSconfig on the root page and then test again?

`tx_html5mediaelements.audio.mp3 >`

If that didn't work, replace that line with:

`tx_html5mediaelements.audio.ogg >`

and then test again? This way you could find out if the error affects only one output format (mp3 or ogg).

**Comment by Danny-P** [comment]
I added this code to the page TSconfig on my root page of the Website. 
Unfortunantelly nothing changed. I tried both variants, but got still the same error.

**Comment by s2b** [comment]
I don't know if this will help, but could you provide a sample file? I'll try to convert the file with my setup.

**Comment by Danny-P** [comment]
Yes, of course. 
You can find the file here: http://cms.danielpomrehn.net/fileadmin/thw_grevenbroich/tmp/interview.mp3

**Comment by s2b** [comment]
I could reproduce the behavior in my test environment. Internally the following ffmpeg command will be executed:

`/usr/local/bin/ffmpeg '-i' '/path/to/typo3/fileadmin/user_upload/interview.mp3' '-q' '4' '-f' 'mp3' '-strict' 'experimental' '-threads' '1' '-acodec' 'mp3' '/path/to/typo3/typo3temp/phpvideotoolkit/files/interview-u_12496_1555j_1454076912.mp3' '-q' '4' '-f' 'oga' '-strict' 'experimental' '-threads' '1' '-acodec' 'vorbis' '/path/to/typo3/typo3temp/phpvideotoolkit/files/interview-u_66800_q9xck_1454076912.oga'`

However, if I insert one of the lines I wrote above to my page TSconfig (!), the conversion works:

`tx_html5mediaelements.audio.ogg >`

I can also reproduce this if I remove the ogg conversion from the ffmpeg command above:

`/usr/local/bin/ffmpeg '-i' '/path/to/typo3/fileadmin/user_upload/interview.mp3' '-q' '4' '-f' 'mp3' '-strict' 'experimental' '-threads' '1' '-acodec' 'mp3' '/path/to/typo3/typo3temp/phpvideotoolkit/files/interview-u_12496_1555j_1454076912.mp3'`

This means that ffmpeg somehow can't convert your file to the ogg format, however the mp3 conversion works just fine.

As I'm not a real expert in audio formats I don't really know what you could do to fix this. However you could just disable the ogg conversion with the page TSconfig line from above as all current browsers support mp3 files anyways and the others will just fallback to Flash.

**Comment by Danny-P** [comment]
Hi,
I don't know what was wrong... I killed the extensions, ffmpeg and so on from my System and started from scatch. I did exakt the same, and now it works.
Thank you very much for your assistence! 
Best regards
Daniel
